# Generated by Django 3.2.15 on 2023-08-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_alter_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uuid',
            new_name='user_id',
        ),
    ]
